# Generated by Django 4.2.2 on 2023-08-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rorapp", "0019_completedaction_faction_completedaction_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedaction",
            name="parameters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="potentialaction",
            name="parameters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
