# Generated by Django 4.2.3 on 2024-02-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rorapp", "0049_rename_naval_defeated_war_undefeated_navy"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnemyLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=13)),
                ("strength", models.IntegerField()),
                ("disaster_number", models.IntegerField()),
                ("standoff_number", models.IntegerField()),
                ("war_name", models.CharField(max_length=10)),
                ("dead", models.BooleanField()),
                (
                    "current_war",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rorapp.war"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rorapp.game"
                    ),
                ),
            ],
        ),
    ]
