# Generated by Django 4.2.3 on 2024-05-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rorapp", "0058_rename_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=19)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rorapp.game"
                    ),
                ),
                (
                    "senator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rorapp.senator",
                    ),
                ),
            ],
        ),
    ]
