# Generated by Django 5.0.7 on 2025-02-06 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    def delete_games(apps, schema_editor):
        Game = apps.get_model("rorapp", "Game")
        Game.objects.all().delete()

    dependencies = [
        ("rorapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_games, migrations.RunPython.noop),  # type: ignore
        migrations.AddField(
            model_name="game",
            name="host",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='creation_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
