# Generated by Django 5.0.7 on 2025-02-09 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rorapp",
            "0004_game_started_on_faction_faction_unique_game_position_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factions",
                to="rorapp.game",
            ),
        ),
    ]
