# Generated by Django 4.1.1 on 2023-03-24 16:40
# Edited by Logan on 2023-03-24 16:42: added the delete_games_without_owner operation

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def delete_games_without_owner(apps, schema_editor):
    Game = apps.get_model('rorapp', 'Game')
    Game.objects.filter(owner=None).delete()
    
        
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rorapp', '0008_alter_game_creation_date'),
    ]

    operations = [
        migrations.RunPython(delete_games_without_owner),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
