# Generated by Django 4.2.2 on 2023-06-18 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0011_rename_owner_game_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
