# Generated by Django 5.0.7 on 2025-02-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0011_availableaction_schema_faction_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="senator",
            name="status",
            field=models.JSONField(default=list),
        )
    ]
