# Generated by Django 4.2.2 on 2023-07-03 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0012_waitlistentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'verbose_name_plural': 'waitlist entries'},
        ),
    ]
