# Generated by Django 5.0.7 on 2025-02-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0012_senator_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availableaction",
            name="schema",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="faction",
            name="cards",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="faction",
            name="status",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="senator",
            name="status",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
