# Generated by Django 5.0.7 on 2025-03-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0019_alter_game_sub_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableaction',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
