# Generated by Django 4.2.2 on 2023-08-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0021_rename_gameparticipant_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamilySenator',
            new_name='Senator',
        ),
    ]
