# Generated by Django 5.0.7 on 2025-03-17 21:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0021_game_deck_alter_game_sub_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="War",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("series_name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "index",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "land_strength",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "fleet_support",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "naval_strength",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("disaster_numbers", models.JSONField(blank=True, default=list)),
                ("standoff_numbers", models.JSONField(blank=True, default=list)),
                (
                    "spoils",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("famine", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Inactive", "Inactive"),
                            ("Imminent", "Imminent"),
                            ("Active", "Active"),
                            ("Unprosecuted", "Unprosecuted"),
                            ("Defeated", "Defeated"),
                        ],
                        max_length=12,
                    ),
                ),
                ("undefeated_navy", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wars",
                        to="rorapp.game",
                    ),
                ),
            ],
        ),
    ]
