# Generated by Django 5.0.7 on 2025-03-21 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0022_war"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="unrest",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
