# Generated by Django 5.0.7 on 2025-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0025_game_combat_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(blank=True, choices=[('Initial', 'Initial'), ('Mortality', 'Mortality'), ('Revenue', 'Revenue'), ('Forum', 'Forum'), ('Population', 'Population'), ('Senate', 'Senate'), ('Combat', 'Combat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='phase',
            field=models.CharField(blank=True, choices=[('Initial', 'Initial'), ('Mortality', 'Mortality'), ('Revenue', 'Revenue'), ('Forum', 'Forum'), ('Population', 'Population'), ('Senate', 'Senate'), ('Combat', 'Combat')], max_length=20, null=True),
        ),
    ]
