# Generated by Django 5.0.7 on 2025-05-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0026_alter_log_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Initial", "Initial"),
                    ("Mortality", "Mortality"),
                    ("Revenue", "Revenue"),
                    ("Forum", "Forum"),
                    ("Population", "Population"),
                    ("Senate", "Senate"),
                    ("Combat", "Combat"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Initial", "Initial"),
                    ("Mortality", "Mortality"),
                    ("Revenue", "Revenue"),
                    ("Forum", "Forum"),
                    ("Population", "Population"),
                    ("Senate", "Senate"),
                    ("Combat", "Combat"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
