# Generated by Django 5.0.7 on 2025-07-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0026_alter_log_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="current_proposal",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="defeated_proposals",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="votes_nay",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="votes_yea",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="deck",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="game",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Initial", "Initial"),
                    ("Mortality", "Mortality"),
                    ("Revenue", "Revenue"),
                    ("Forum", "Forum"),
                    ("Population", "Population"),
                    ("Senate", "Senate"),
                    ("Combat", "Combat"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="sub_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Attract knight", "Attract knight"),
                    ("Consular election", "Consular election"),
                    ("End", "End"),
                    ("Faction leader", "Faction leader"),
                    ("Initiative auction", "Initiative auction"),
                    ("Initiative roll", "Initiative roll"),
                    ("Redistribution", "Redistribution"),
                    ("Sponsor games", "Sponsor games"),
                    ("Start", "Start"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Initial", "Initial"),
                    ("Mortality", "Mortality"),
                    ("Revenue", "Revenue"),
                    ("Forum", "Forum"),
                    ("Population", "Population"),
                    ("Senate", "Senate"),
                    ("Combat", "Combat"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
