# Generated by Django 5.0.7 on 2025-05-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0027_alter_game_phase_alter_log_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="current_proposal",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="defeated_proposals",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="game",
            name="sub_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Attract knight", "Attract knight"),
                    ("Consular election", "Consular election"),
                    ("End", "End"),
                    ("Faction leader", "Faction leader"),
                    ("Initiative auction", "Initiative auction"),
                    ("Initiative roll", "Initiative roll"),
                    ("Redistribution", "Redistribution"),
                    ("Sponsor games", "Sponsor games"),
                    ("Start", "Start"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
