# Generated by Django 4.2.2 on 2023-09-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
