# Generated by Django 4.2.2 on 2023-09-12 07:02
# Edited by Logan on 2023-09-12: added the load_data operation
# This migration depends on 0029_migration_data.json

from django.db import migrations, models
import json
from pathlib import Path

# This migration adds senator codes, which are loaded from a JSON file.
def load_data(apps, schema_editor):
    Senator = apps.get_model('rorapp', 'Senator')
    
    with open(Path(__file__).resolve().parent / '0029_migration_data.json') as f:
        data = json.load(f)

    for name, code in data.items():
        senators = Senator.objects.filter(name=name)
        for senator in senators:
            senator.code = code
            senator.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0028_senator_alive_alter_senator_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(load_data, migrations.RunPython.noop),
    ]
