# Generated by Django 5.0.7 on 2025-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0028_fleet_legion_remove_faction_unique_game_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='location',
            field=models.CharField(default='Rome', max_length=20),
        ),
    ]
