# Generated by Django 5.0.7 on 2025-07-22 09:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0028_campaign_fleet_legion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombatCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("land_battle", models.BooleanField(default=True)),
                (
                    "legions",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "veteran_legions",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "fleets",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "commander",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_calculations",
                        to="rorapp.senator",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_calculations",
                        to="rorapp.game",
                    ),
                ),
                (
                    "war",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_calculations",
                        to="rorapp.war",
                    ),
                ),
            ],
        ),
    ]
