# Generated by Django 5.0.7 on 2025-05-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0028_game_current_proposal_game_defeated_proposals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="votes_nay",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="votes_yea",
            field=models.IntegerField(default=0),
        ),
    ]
