# Generated by Django 5.0.7 on 2025-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0029_game_votes_nay_game_votes_yea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='defeated_proposals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
