# Generated by Django 5.0.7 on 2025-11-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0030_campaign_imminent_campaign_pending_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="war",
            name="undefeated_navy",
        ),
    ]
