# Generated by Django 5.0.7 on 2025-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0031_remove_war_undefeated_navy"),
    ]

    operations = [
        migrations.AddField(
            model_name="war",
            name="spent_disaster_numbers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="war",
            name="spent_standoff_numbers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
