# Generated by Django 5.0.7 on 2025-11-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0032_war_spent_disaster_numbers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="commander",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="rorapp.senator",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fleets",
                to="rorapp.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="legion",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legions",
                to="rorapp.campaign",
            ),
        ),
    ]
