# Generated by Django 5.0.7 on 2025-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0033_alter_campaign_commander_alter_fleet_campaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="war",
            name="fought_land_battle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="war",
            name="fought_naval_battle",
            field=models.BooleanField(default=False),
        ),
    ]
