# Generated by Django 4.2.2 on 2023-09-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0033_senatornotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenatorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Notification',
            new_name='ActionLog',
        ),
        migrations.DeleteModel(
            name='SenatorNotification',
        ),
        migrations.AddField(
            model_name='senatoractionlog',
            name='action_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rorapp.actionlog'),
        ),
        migrations.AddField(
            model_name='senatoractionlog',
            name='senator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rorapp.senator'),
        ),
    ]
