# Generated by Django 4.2.2 on 2023-09-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0033_senatornotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SenatorNotification',
            new_name='SenatorActionLog',
        ),
        migrations.RenameModel(
            old_name='Notification',
            new_name='ActionLog',
        ),
        migrations.RenameField(
            model_name='senatoractionlog',
            old_name='notification',
            new_name='action_log',
        ),
    ]
