# Generated by Django 5.0.7 on 2025-11-13 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0034_war_fought_land_battle_war_fought_naval_battle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combatcalculation",
            name="commander",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="combat_calculations",
                to="rorapp.senator",
            ),
        ),
        migrations.AlterField(
            model_name="combatcalculation",
            name="war",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="combat_calculations",
                to="rorapp.war",
            ),
        ),
    ]
