# Generated by Django 5.0.7 on 2025-11-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0035_alter_combatcalculation_commander_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="combatcalculation",
            old_name="legions",
            new_name="regular_legions",
        ),
    ]
