# Generated by Django 4.2.2 on 2023-10-08 13:55

from django.db import migrations, models
import django.db.models.deletion


def convert_alive_to_senator_death(apps, schema_editor):
    Senator = apps.get_model('rorapp', 'Senator')
    dead_senators = Senator.objects.filter(alive=False)

    ActionLog = apps.get_model('rorapp', 'ActionLog')
    death_action_logs = ActionLog.objects.filter(type='face_mortality')

    for dead_action_log in death_action_logs:
        if (dead_action_log.data is None):
            continue
        dead_senator_id = dead_action_log.data.get('senator')
        if (dead_senator_id is None):
            continue
        dead_senator = dead_senators.get(id=dead_senator_id)
        dead_senator.death_step = dead_action_log.step
        dead_senator.save()


def convert_senator_death_to_alive(apps, schema_editor):
    Senator = apps.get_model('rorapp', 'Senator')
    dead_senators = Senator.objects.filter(death_step__isnull=False)
    dead_senators.update(alive=False)


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0035_alter_faction_game_alter_player_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='death_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rorapp.step'),
        ),
        migrations.RunPython(convert_alive_to_senator_death, convert_senator_death_to_alive),
        migrations.RemoveField(
            model_name='senator',
            name='alive',
        ),
    ]
