# Generated by Django 5.0.7 on 2025-11-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0036_rename_legions_combatcalculation_regular_legions"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="password",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
