# Generated by Django 4.2.2 on 2023-11-13 19:31

from django.db import migrations, models


def move_completed_to_potential(apps, schema_editor):
    PotentialAction = apps.get_model("rorapp", "PotentialAction")
    CompletedAction = apps.get_model("rorapp", "CompletedAction")
    for completedAction in CompletedAction.objects.all():
        new_action = PotentialAction(
            step=completedAction.step,
            faction=completedAction.faction,
            type=completedAction.type,
            required=completedAction.required,
            parameters=completedAction.parameters,
            completed=True,
        )
        new_action.save()
    CompletedAction.objects.all().delete()


def move_potential_back_to_completed(apps, schema_editor):
    PotentialAction = apps.get_model('rorapp', 'PotentialAction')
    CompletedAction = apps.get_model('rorapp', 'CompletedAction')
    for potentialAction in PotentialAction.objects.filter(completed=True):
        new_completed_action = CompletedAction(
            step=potentialAction.step,
            faction=potentialAction.faction,
            type=potentialAction.type,
            required=potentialAction.required,
            parameters=potentialAction.parameters,
        )
        new_completed_action.save()
    PotentialAction.objects.filter(completed=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("rorapp", "0037_dead_senators_faction"),
    ]

    operations = [
        migrations.AddField(
            model_name="potentialaction",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(move_completed_to_potential, move_potential_back_to_completed),
    ]
