# Generated by Django 5.0.7 on 2025-11-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0037_game_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="recently_deployed_or_reinforced",
            field=models.BooleanField(default=True),
        ),
    ]
