# Generated by Django 5.0.7 on 2026-01-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0038_campaign_recently_deployed_or_reinforced"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="recently_deployed_or_reinforced",
            new_name="recently_deployed",
        ),
        migrations.AddField(
            model_name="campaign",
            name="recently_reinforced",
            field=models.BooleanField(default=False),
        ),
    ]
