# Generated by Django 5.0.7 on 2026-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0040_rename_name_to_base_name_add_variant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="concessions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="senator",
            name="concessions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="senator",
            name="corrupt_concessions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
