# Generated by Django 5.0.7 on 2026-02-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0041_game_concessions_senator_concessions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Initial", "Initial"),
                    ("Mortality", "Mortality"),
                    ("Revenue", "Revenue"),
                    ("Forum", "Forum"),
                    ("Population", "Population"),
                    ("Senate", "Senate"),
                    ("Combat", "Combat"),
                    ("Revolution", "Revolution"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="sub_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Attract knight", "Attract knight"),
                    ("Consular election", "Consular election"),
                    ("End", "End"),
                    ("Faction leader", "Faction leader"),
                    ("Initiative auction", "Initiative auction"),
                    ("Initiative roll", "Initiative roll"),
                    ("Other business", "Other business"),
                    ("Redistribution", "Redistribution"),
                    ("Resolution", "Resolution"),
                    ("Sponsor games", "Sponsor games"),
                    ("Start", "Start"),
                    ("Play statesmen/concessions", "Play statesmen/concessions"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Initial", "Initial"),
                    ("Mortality", "Mortality"),
                    ("Revenue", "Revenue"),
                    ("Forum", "Forum"),
                    ("Population", "Population"),
                    ("Senate", "Senate"),
                    ("Combat", "Combat"),
                    ("Revolution", "Revolution"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
