# Generated by Django 4.2.3 on 2024-01-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0042_assign_prior_consul_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('W', 'war'), ('S', 'senator'), ('M', 'statesman'), ('L', 'leader'), ('I', 'intrigue'), ('C', 'concession')], max_length=10)),
                ('secret', models.BooleanField()),
                ('index', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rorapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('M', 'statesman'), ('I', 'intrigue'), ('C', 'concession')], max_length=10)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rorapp.faction')),
            ],
        ),
    ]
