# Generated by Django 4.2.3 on 2024-02-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0044_shuffle_situations'),
    ]

    operations = [
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('index', models.IntegerField()),
                ('land_strength', models.IntegerField()),
                ('naval_support', models.IntegerField()),
                ('naval_strength', models.IntegerField()),
                ('disaster_numbers', models.JSONField()),
                ('standoff_numbers', models.JSONField()),
                ('spoils', models.IntegerField()),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('imminent', 'imminent'), ('active', 'active'), ('unprosecuted', 'unprosecuted'), ('defeated', 'defeated')], max_length=12)),
                ('famine', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rorapp.game')),
            ],
        ),
    ]
