# Generated by Django 4.2.3 on 2024-02-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def create_first_punic_war(apps, schema_editor):
        Game = apps.get_model("rorapp", "Game")
        War = apps.get_model("rorapp", "War")
        Situation = apps.get_model("rorapp", "Situation")
        Situation.objects.filter(name="1st Punic War").delete()
        games = Game.objects.filter(start_date__isnull=False)
        for game in games:
            first_punic_war = War(
                name="Punic",
                index=1,
                game=game,
                land_strength=10,
                fleet_support=5,
                naval_strength=10,
                disaster_numbers=[13],
                standoff_numbers=[11, 14],
                spoils=35,
                status="inactive",
                famine=False,
                naval_defeated=False,
            )
            first_punic_war.save()

    dependencies = [
        ("rorapp", "0044_shuffle_situations"),
    ]

    operations = [
        migrations.CreateModel(
            name="War",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("index", models.IntegerField()),
                ("land_strength", models.IntegerField()),
                ("fleet_support", models.IntegerField()),
                ("naval_strength", models.IntegerField()),
                ("disaster_numbers", models.JSONField()),
                ("standoff_numbers", models.JSONField()),
                ("spoils", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "inactive"),
                            ("imminent", "imminent"),
                            ("active", "active"),
                            ("unprosecuted", "unprosecuted"),
                            ("defeated", "defeated"),
                        ],
                        max_length=12,
                    ),
                ),
                ("famine", models.BooleanField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rorapp.game"
                    ),
                ),
                ("naval_defeated", models.BooleanField()),
            ],
        ),
        migrations.RunPython(create_first_punic_war, migrations.RunPython.noop),
    ]
