# Generated by Django 5.1.15 on 2026-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0045_add_card_trading_subphase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="sub_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("attract knight", "attract knight"),
                    ("censor election", "censor election"),
                    ("consular election", "consular election"),
                    ("end", "end"),
                    ("faction leader", "faction leader"),
                    ("initiative auction", "initiative auction"),
                    ("initiative roll", "initiative roll"),
                    ("other business", "other business"),
                    ("prosecution", "prosecution"),
                    ("redistribution", "redistribution"),
                    ("resolution", "resolution"),
                    ("sponsor games", "sponsor games"),
                    ("start", "start"),
                    ("card trading", "card trading"),
                    ("play statesmen/concessions", "play statesmen/concessions"),
                    ("putting Rome in order", "putting Rome in order"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
