# Generated by Django 5.1.15 on 2026-03-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0046_alter_game_sub_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnemyLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("series_name", models.CharField(max_length=20)),
                ("strength", models.IntegerField()),
                ("disaster_number", models.IntegerField()),
                ("standoff_number", models.IntegerField()),
                ("active", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enemy_leaders",
                        to="rorapp.game",
                    ),
                ),
            ],
        ),
    ]
