# Generated by Django 4.2.3 on 2024-02-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0047_syrian_war_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='war',
            name='matching_wars',
            field=models.ManyToManyField(to='rorapp.war'),
        ),
    ]
