# Generated by Django 5.1.15 on 2026-04-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0049_game_effects_alter_game_sub_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="sub_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("attract knight", "attract knight"),
                    ("censor election", "censor election"),
                    ("consular election", "consular election"),
                    ("end", "end"),
                    ("faction leader", "faction leader"),
                    ("initiative auction", "initiative auction"),
                    ("initiative roll", "initiative roll"),
                    ("other business", "other business"),
                    ("prosecution", "prosecution"),
                    ("redistribution", "redistribution"),
                    ("resolution", "resolution"),
                    ("sponsor games", "sponsor games"),
                    ("start", "start"),
                    ("card trading", "card trading"),
                    ("play statesmen/concessions", "play statesmen/concessions"),
                    ("persuasion attempt", "persuasion attempt"),
                    ("persuasion counter-bribe", "persuasion counter-bribe"),
                    ("persuasion decision", "persuasion decision"),
                    ("putting Rome in order", "putting Rome in order"),
                    ("era ends", "era ends"),
                    ("state of the Republic speech", "state of the Republic speech"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
