# Generated by Django 5.1.15 on 2026-04-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0050_alter_game_sub_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatcalculation",
            name="is_dictator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="combatcalculation",
            name="master_of_horse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moh_combat_calculations",
                to="rorapp.senator",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="master_of_horse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supporting_campaigns",
                to="rorapp.senator",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="sub_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("attract knight", "attract knight"),
                    ("censor election", "censor election"),
                    ("consular election", "consular election"),
                    ("dictator appointment", "dictator appointment"),
                    ("dictator election", "dictator election"),
                    ("end", "end"),
                    ("faction leader", "faction leader"),
                    ("master of horse appointment", "master of horse appointment"),
                    ("initiative auction", "initiative auction"),
                    ("initiative roll", "initiative roll"),
                    ("other business", "other business"),
                    ("prosecution", "prosecution"),
                    ("redistribution", "redistribution"),
                    ("resolution", "resolution"),
                    ("sponsor games", "sponsor games"),
                    ("start", "start"),
                    ("card trading", "card trading"),
                    ("play statesmen/concessions", "play statesmen/concessions"),
                    ("persuasion attempt", "persuasion attempt"),
                    ("persuasion counter-bribe", "persuasion counter-bribe"),
                    ("persuasion decision", "persuasion decision"),
                    ("putting Rome in order", "putting Rome in order"),
                    ("era ends", "era ends"),
                    ("state of the Republic speech", "state of the Republic speech"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
