# Generated by Django 4.2.3 on 2024-03-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    
    def populate_dead_field(apps, schema_editor):
        Senator = apps.get_model('rorapp', 'Senator')
        for senator in Senator.objects.all():
            senator.alive = senator.death_step is None
            senator.save()

    dependencies = [
        ('rorapp', '0052_alter_enemyleader_current_war'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='alive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_dead_field, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='senator',
            name='death_step',
        ),
    ]
