# Generated by Django 4.2.3 on 2024-03-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0053_senator_dead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemyleader',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='senator',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
