# Generated by Django 5.1.15 on 2026-06-16 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0055_add_evil_omens_to_combat_calculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('developed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='rorapp.game')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('game', 'name'), name='unique_province_game_name'
                    ),
                ],
            },
        ),
    ]
