# Generated by Django 5.1.15 on 2026-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0058_legion_allegiance_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='consul_for_life_appointed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='consul_for_life_proposed',
            field=models.BooleanField(default=False),
        ),
    ]
