# Generated by Django 4.2.3 on 2024-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0059_concession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession',
            name='name',
            field=models.CharField(max_length=19),
        ),
    ]
