# Generated by Django 4.2.3 on 2024-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0059_concession'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='custom_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
