# Generated by Django 5.1.15 on 2026-08-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0060_game_consul_for_life_appointed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='destroyed_concessions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
