# Generated by Django 5.1.15 on 2026-09-12 00:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0063_defeated_war_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='rebel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='war',
            name='primary_rebel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revolts', to='rorapp.senator'),
        ),
        migrations.AlterField(
            model_name='war',
            name='land_strength',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
