# Generated by Django 5.1.15 on 2026-09-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0064_game_storm_at_sea_fleet_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='rebel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='war',
            name='primary_rebel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revolts', to='rorapp.senator'),
        ),
    ]
