# Generated by Django 5.2.16 on 2026-09-20

from django.db import migrations, models


def migrate_antiochus_to_individual_war(apps, schema_editor):
    EnemyLeader = apps.get_model("rorapp", "EnemyLeader")
    EnemyLeader.objects.filter(
        name="Antiochus III", series_name="Syrian"
    ).update(series_name=None, war_name="Syrian War")


def restore_antiochus_series(apps, schema_editor):
    EnemyLeader = apps.get_model("rorapp", "EnemyLeader")
    EnemyLeader.objects.filter(
        name="Antiochus III", series_name__isnull=True, war_name="Syrian War"
    ).update(series_name="Syrian", war_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ("rorapp", "0065_rebels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enemyleader",
            name="series_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="enemyleader",
            name="war_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(
            migrate_antiochus_to_individual_war,
            restore_antiochus_series,
        ),
    ]
