# Generated by Django 5.1.15 on 2026-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0065_rebels'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rhodian_alliance_rejectable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='war',
            name='rhodian_alliance',
            field=models.BooleanField(default=False),
        ),
    ]
