# Generated by Django 5.1.15 on 2026-09-16 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0065_rebels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war',
            name='land_strength',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
