# Generated by Django 5.1.15 on 2026-09-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0066_senator_curia_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='captor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captives', to='rorapp.war'),
        ),
    ]
