# Generated by Django 5.1.15 on 2026-09-20 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0066_province_governor'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='term',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
