# Generated by Django 5.1.15 on 2026-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0067_province_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='recently_elected',
            field=models.BooleanField(default=False),
        ),
    ]
