# Generated by Django 5.2.16 on 2026-10-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0070_game_new_alliance_sub_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_decisions', to='rorapp.faction')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_decisions', to='rorapp.game')),
            ],
        ),
    ]
