version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:5
    ports:
      - 6379:6379

  web:
    build: .
    command: [ "/app/server/start.sh" ]
    volumes:
      - .:/code
      - static_volume:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: secret_key
      FRONTEND_ORIGIN: http://localhost:3000
      RDS_USERNAME: postgres
      RDS_PASSWORD: postgres
      RDS_HOSTNAME: db
      RDS_PORT: 5432
      RDS_NAME: postgres
      REDIS_HOSTNAME: redis
      DEBUG: "True"

volumes:
  static_volume:
