version: '3.8'

services:
  redis:
    image: redis:5
    ports:
      - 6379:6379

  web:
    build: .
    command: ["/app/server/start.sh"]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - 8000:80
    depends_on:
      - redis
    environment:
      SECRET_KEY: ${SECRET_KEY}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_HOSTNAME: host.docker.internal
      RDS_PORT: ${RDS_PORT}
      RDS_NAME: ${RDS_NAME}
      REDIS_HOSTNAME: redis
      DEBUG: "True"

volumes:
  static_volume:
