version: '3.8'

services:
  redis:
    image: redis:5
    ports:
      - 6379:6379

  web:
    build: .
    command: [ "/app/server/start.sh" ]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - 8000:80
    depends_on:
      - redis
    environment:
      ALLOWED_HOSTS: 127.0.0.1
      FRONTEND_ORIGIN: http://127.0.0.1:3000
      DEBUG: "True"
      PARENT_DOMAIN: 127.0.0.1
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_HOSTNAME: host.docker.internal
      RDS_PORT: ${RDS_PORT}
      RDS_NAME: ${RDS_NAME}
      SECRET_KEY: secret_key

volumes:
  static_volume:
