from typing import List, Type
from rorapp.effects import *
from rorapp.effects.meta.effect_base import EffectBase


effect_registry: List[Type[EffectBase]] = [
    # High priority
    RebelEndGameStartEffect,
    RebelEndGameResolutionEffect,
    RebelUnopposedEffect,
    RebelWinsOnCollapseEffect,
    GameOverStateBankruptcyEffect,
    GameOverMilitaryOverwhelmedEffect,
    GameOverEraEndsEffect,
    GameOverConsulForLifeEffect,
    AppointConsulForLifeEffect,
    # Standard priority
    CombatPhaseEndEffect,
    CombatResolutionEffect,
    CombatPhaseStartEffect,
    AutoAppointCensorEffect,
    AutoCloseProsecutionsEffect,
    DictatorAppointmentResolveEffect,
    ElectCensorEffect,
    ElectConsulsEffect,
    ElectConsulForLifeEffect,
    ElectDictatorEffect,
    ResolveProsecutionEffect,
    InitialPhaseDoneEffect,
    InitialPlayCardsDoneEffect,
    InitiativeAuctionAutoPayEffect,
    InitiativeAuctionAutoSkipEffect,
    InitiativeAuctionFirstEffect,
    InitiativeAuctionNextEffect,
    PersuasionAutoSkipEffect,
    PlayCardsAutoSkipEffect,
    PersuasionCounterBribeFirstEffect,
    PersuasionCounterBribeNextEffect,
    PersuasionDecisionAutoResolveEffect,
    InitiativeFirstEffect,
    InitiativeNextEffect,
    PuttingRomeInOrderEffect,
    InitiativeRollEffect,
    MortalityEffect,
    PopulationEffect,
    PreferredAttackerEffect,
    PreferredConsularOfficesEffect,
    ProposalAwardConcessionEffect,
    ProposalLandBillEffect,
    ProposalLandBillRepealEffect,
    ProposalDeployForcesEffect,
    ProposalDisbandForcesEffect,
    ProposalRaiseForcesEffect,
    ProposalRecallForcesEffect,
    ProposalReinforceProconsulEffect,
    ProposalReplaceProconsulEffect,
    RedistributionDoneEffect,
    RevenueEffect,
    ReleasedForcesEliminatedEffect,
    RebelMaintenanceDoneEffect,
    CardTradingDoneEffect,
    PlayCardsDoneEffect,
    CivilWarDeclarationDoneEffect,
    SecondaryRebelsDoneEffect,
    RevolutionPhaseStartEffect,
    RevolutionPhaseEndEffect,
    SenatePhaseEndEffect,
    SenatePhaseStartEffect,
    KnightAutoSkipEffect,
    SponsorGamesAutoSkipEffect,
    RollAssassinationDiceEffect,
    BodyguardCatchRerollEffect,
    ResolveAssassinationEffect,
]
