from typing import List, Type
from rorapp.effects import *
from rorapp.effects.meta.effect_base import EffectBase


effect_registry: List[Type[EffectBase]] = [
    # High priority
    AppointConsulForLifeEffect,
    GameOverConsulForLifeEffect,
    GameOverEraEndsEffect,
    GameOverMilitaryOverwhelmedEffect,
    GameOverStateBankruptcyEffect,
    # Standard priority
    AutoAppointCensorEffect,
    AutoCloseProsecutionsEffect,
    BodyguardCatchRerollEffect,
    CancelSpecialMajorProsecutionEffect,
    CardTradingDoneEffect,
    CombatPhaseEndEffect,
    CombatPhaseStartEffect,
    CombatResolutionEffect,
    DictatorAppointmentResolveEffect,
    ElectCensorEffect,
    ElectConsulForLifeEffect,
    ElectConsulsEffect,
    ElectDictatorEffect,
    FactionLeaderAutoSkipEffect,
    InitialPhaseDoneEffect,
    InitialPlayCardsDoneEffect,
    InitiativeAuctionAutoPayEffect,
    InitiativeAuctionAutoSkipEffect,
    InitiativeAuctionFirstEffect,
    InitiativeAuctionNextEffect,
    InitiativeFirstEffect,
    InitiativeNextEffect,
    InitiativeRollEffect,
    KnightAutoSkipEffect,
    LayDownCommandEffect,
    MortalityEffect,
    NewAllianceEffect,
    PersuasionAutoSkipEffect,
    PersuasionCounterBribeFirstEffect,
    PersuasionCounterBribeNextEffect,
    PersuasionDecisionAutoResolveEffect,
    PlayCardsAutoSkipEffect,
    PlayCardsDoneEffect,
    PopulationEffect,
    PreferredAttackerEffect,
    PreferredConsularOfficesEffect,
    ProposalAwardConcessionEffect,
    ProposalDeployForcesEffect,
    ProposalDisbandForcesEffect,
    ProposalLandBillEffect,
    ProposalLandBillRepealEffect,
    ProposalRaiseForcesEffect,
    ProposalRecallForcesEffect,
    ProposalReinforceProconsulEffect,
    ProposalReplaceProconsulEffect,
    PuttingRomeInOrderEffect,
    ReleasedForcesMaintenanceEffect,
    RebelForcesReleaseEffect,
    RedistributionDoneEffect,
    RepopulateRomeEffect,
    ResolveAssassinationEffect,
    ResolveProsecutionEffect,
    ResolveSpecialMajorProsecutionEffect,
    RevenueEffect,
    RevoltDeclarationNextEffect,
    RevolutionPhaseEndEffect,
    RevolutionPhaseStartEffect,
    RollAssassinationDiceEffect,
    SenatePhaseEndEffect,
    SenatePhaseStartEffect,
    SpecialMajorProsecutionAppealEffect,
    SponsorGamesAutoSkipEffect,
]
