from typing import List, Type
from rorapp.effects import *
from rorapp.effects.meta.effect_base import EffectBase


effect_registry: List[Type[EffectBase]] = [
    # High priority
    GameOverStateBankruptcyEffect,
    GameOverMilitaryOverwhelmedEffect,
    GameOverEraEndsEffect,
    # Standard priority
    CombatPhaseEndEffect,
    CombatResolutionEffect,
    CombatPhaseStartEffect,
    AutoAppointCensorEffect,
    AutoCloseProsecutionsEffect,
    DictatorAppointmentResolveEffect,
    ElectCensorEffect,
    ElectConsulsEffect,
    ElectDictatorEffect,
    ResolveProsecutionEffect,
    InitialPhaseDoneEffect,
    InitialPlayCardsDoneEffect,
    InitiativeAuctionAutoPayEffect,
    InitiativeAuctionAutoSkipEffect,
    InitiativeAuctionFirstEffect,
    InitiativeAuctionNextEffect,
    PersuasionAutoSkipEffect,
    PlayCardsAutoSkipEffect,
    PersuasionCounterBribeFirstEffect,
    PersuasionCounterBribeNextEffect,
    PersuasionDecisionAutoResolveEffect,
    InitiativeFirstEffect,
    InitiativeNextEffect,
    PuttingRomeInOrderEffect,
    InitiativeRollEffect,
    MortalityEffect,
    PopulationEffect,
    PreferredAttackerEffect,
    PreferredConsularOfficesEffect,
    ProposalAwardConcessionEffect,
    ProposalLandBillEffect,
    ProposalLandBillRepealEffect,
    ProposalDeployForcesEffect,
    ProposalRaiseForcesEffect,
    ProposalRecallForcesEffect,
    ProposalReinforceProconsulEffect,
    ProposalReplaceProconsulEffect,
    RedistributionDoneEffect,
    RevenueEffect,
    CardTradingDoneEffect,
    RevolutionPhaseStartEffect,
    RevolutionPhaseEndEffect,
    SenatePhaseEndEffect,
    SenatePhaseStartEffect,
    SponsorGamesAutoSkipEffect,
    RollAssassinationDiceEffect,
    BodyguardCatchRerollEffect,
    ResolveAssassinationEffect,
]
