from typing import Dict, Type
from rorapp.actions import *
from rorapp.actions.meta.action_base import ActionBase


action_registry: Dict[str, Type[ActionBase]] = {
    AbstainAction.NAME: AbstainAction,
    AppointDictatorAction.NAME: AppointDictatorAction,
    AcceptProsecutorRoleAction.NAME: AcceptProsecutorRoleAction,
    AcceptRiskyCommandAction.NAME: AcceptRiskyCommandAction,
    FightLandBattleAction.NAME: FightLandBattleAction,
    GiveSpeechAction.NAME: GiveSpeechAction,
    AttractKnightAction.NAME: AttractKnightAction,
    AttemptPersuasionAction.NAME: AttemptPersuasionAction,
    CounterBribeAction.NAME: CounterBribeAction,
    ContinuePersuasionAction.NAME: ContinuePersuasionAction,
    HaltAfterNavalVictoryAction.NAME: HaltAfterNavalVictoryAction,
    CloseSenateAction.NAME: CloseSenateAction,
    ContributeAction.NAME: ContributeAction,
    DoneAction.NAME: DoneAction,
    DoneNotAction.NAME: DoneNotAction,
    CallPopularAppealAction.NAME: CallPopularAppealAction,
    ElectCensorAction.NAME: ElectCensorAction,
    ElectConsulsAction.NAME: ElectConsulsAction,
    ElectDictatorAction.NAME: ElectDictatorAction,
    ProposeMajorProsecutionAction.NAME: ProposeMajorProsecutionAction,
    ProposeMinorProsecutionAction.NAME: ProposeMinorProsecutionAction,
    CloseProsecutionsAction.NAME: CloseProsecutionsAction,
    FactionLeaderChangeAction.NAME: FactionLeaderChangeAction,
    FactionLeaderKeepAction.NAME: FactionLeaderKeepAction,
    FactionLeaderSelectAction.NAME: FactionLeaderSelectAction,
    InitiativeAuctionBidAction.NAME: InitiativeAuctionBidAction,
    InitiativeAuctionPayAction.NAME: InitiativeAuctionPayAction,
    PlayConcessionAction.NAME: PlayConcessionAction,
    PlayStatesmanAction.NAME: PlayStatesmanAction,
    ProposeAwardingConcessionAction.NAME: ProposeAwardingConcessionAction,
    ProposeDeployingForcesAction.NAME: ProposeDeployingForcesAction,
    ProposeRaisingForcesAction.NAME: ProposeRaisingForcesAction,
    ProposeRecallingForcesAction.NAME: ProposeRecallingForcesAction,
    ProposeReinforcingProconsulAction.NAME: ProposeReinforcingProconsulAction,
    ProposeReplacingProconsulAction.NAME: ProposeReplacingProconsulAction,
    RefuseProsecutorRoleAction.NAME: RefuseProsecutorRoleAction,
    RefuseRiskyCommandAction.NAME: RefuseRiskyCommandAction,
    SelectConsularOfficesAction.NAME: SelectConsularOfficesAction,
    SelectMasterOfHorseAction.NAME: SelectMasterOfHorseAction,
    SelectPreferredAttackerAction.NAME: SelectPreferredAttackerAction,
    SelectPreferredConsularOfficeAction.NAME: SelectPreferredConsularOfficeAction,
    SkipAction.NAME: SkipAction,
    SponsorGamesAction.NAME: SponsorGamesAction,
    RedistributeTalentsAction.NAME: RedistributeTalentsAction,
    TradeCardAction.NAME: TradeCardAction,
    TransferTalentsAction.NAME: TransferTalentsAction,
    CancelTribuneAction.NAME: CancelTribuneAction,
    Lose1Influence.NAME: Lose1Influence,
    StepDownAsPresidingMagistrateAction.NAME: StepDownAsPresidingMagistrateAction,
    PlayTribuneAction.NAME: PlayTribuneAction,
    VetoWithTribuneAction.NAME: VetoWithTribuneAction,
    AdvancedVoteAction.NAME: AdvancedVoteAction,
    CallFactionToVoteAction.NAME: CallFactionToVoteAction,
    VoteNayAction.NAME: VoteNayAction,
    VoteYeaAction.NAME: VoteYeaAction,
}
