from .available_action import AvailableActionAdmin
from .campaign import CampaignAdmin
from .combat_calculation import CombatCalculationAdmin
from .faction import FactionAdmin
from .fleet import FleetAdmin
from .game import GameAdmin
from .legion import LegionAdmin
from .log import LogAdmin
from .senator import SenatorAdmin
from .war import WarAdmin
