name: CI backend

on:
  pull_request:
    branches:
    - main
    paths:
    - 'backend/**'
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Start services
      run: docker-compose -f backend/docker-compose.yml up -d

    - name: Run migrations
      run: docker-compose -f backend/docker-compose.yml run web python manage.py migrate
