name: CI backend

on:
  pull_request:
    branches:
    - main
    paths:
    - 'backend/**'
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend

    - name: Wait for PostgreSQL to become ready
      run: sleep 10
      
    - name: Run migrations
      run: |
        python manage.py migrate
      env:
        DATABASE_URL: postgres://postgres:postgres@db:5432/github_actions
        SECRET_KEY: ${{ secrets.CI_BACKEND__SECRET_KEY }}
        FRONTEND_ORIGIN: ${{ secrets.CI_BACKEND__FRONTEND_ORIGIN }}
        RDS_DB_NAME: postgres
        USERNAME: postgres
        PASSWORD: postgres
        HOSTNAME: db
        PORT: 5432
      working-directory: backend
