name: CI backend

on:
  push:
    branches:
    - main
    paths:
    - 'backend/**'
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django psycopg2-binary
      working-directory: backend

    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
      working-directory: backend

    - name: Run tests
      run: |
        python manage.py test
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
      working-directory: backend
