name: CI frontend

on:
  pull_request:
    branches:
    - main
    paths:
    - 'frontend/**'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache

    - name: Install Dependencies
      run: cd frontend && npm ci

    - name: Build Next.js
      run: cd frontend && npm run build
