name: CI frontend

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ci_frontend_filter:
    runs-on: ubuntu-latest
    outputs:
      file_changes: ${{ steps.changes.outputs.file_changes }}
    steps:
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            file_changes:
              - 'frontend/**'

  ci_frontend:
    needs: ci_frontend_filter
    if: needs.ci_frontend_filter.outputs.file_changes == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: cd frontend && npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          workingDir: frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
